---
- hosts: all
  tasks:
    - name: Install Flask
      apt: pkg={{ item }} state=latest
      loop: 
        - "python3-pip"
        - "python3-dev"
        - "build-essential"
        - "libssl-dev"
        - "libffi-dev"
        - "python3-setuptools"
        - "python3-venv"
      become: yes

    - name: Create a directory if it does not exist
      file:
        path: ~/myproject/
        state: directory
        mode: '0755'

    - name: Create virtual environment
      shell:
        cmd: python3 -m venv myprojectenv
        chdir: ~/myproject/

    - name: Activate virtual environment
      shell:
        cmd: source myprojectenv/bin/activate

